import { resolveRoute, type RoutingEnv } from "./routing";

/**
 * The Tripistic Workers-for-Platforms dispatch Worker.
 *
 * One Worker owns every public site hostname — `*.tripistic.site`, the preview
 * domain, and every verified custom hostname — and forwards each request to the
 * tenant Worker that serves it. That is what makes self-serve websites possible
 * without a Cloudflare route per customer.
 *
 * The security model in one paragraph: **tenants never write code that runs
 * here.** A tenant Worker is generated by `lib/sites/worker-runtime.ts` from
 * Zod-validated structured content, uploaded by Tripistic, and given no
 * secrets — its bindings are pre-rendered pages and a public API origin. This
 * dispatcher holds the signing secret and the namespace binding, and passes
 * neither to the tenant script. A tenant Worker that was somehow malicious
 * still reaches only data that is already public.
 *
 * Everything below is deliberately boring: resolve, dispatch, add headers, and
 * fail to a branded page rather than to a stack trace.
 */

export type Env = RoutingEnv & {
  /** Dispatch-namespace binding. `get(scriptName)` returns a fetcher. */
  DISPATCHER: { get(name: string): { fetch(request: Request): Promise<Response> } };
  ENVIRONMENT?: string;
};

const SECURITY_HEADERS: Record<string, string> = {
  // A tenant site has no reason to be framed, and clickjacking a booking flow
  // is the obvious attack against one.
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  // Nothing a generated site renders needs any of these.
  "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
};

function errorPage(status: number, title: string, message: string): Response {
  // Hand-written, self-contained HTML. Importing a template would couple the
  // dispatcher to the renderer, and this page has to work in exactly the case
  // where something upstream did not.
  const body = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${title}</title>
<style>
:root{color-scheme:light dark}
body{margin:0;min-height:100vh;display:grid;place-items:center;
font:16px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif;
background:#fafaf9;color:#1c1917;padding:2rem}
@media(prefers-color-scheme:dark){body{background:#0c0a09;color:#fafaf9}}
main{max-width:34rem;text-align:center}
h1{font-size:1.35rem;margin:0 0 .5rem;font-weight:600}
p{margin:0;color:#57534e}
@media(prefers-color-scheme:dark){p{color:#a8a29e}}
</style></head><body><main><h1>${title}</h1><p>${message}</p></main></body></html>`;

  return new Response(body, {
    status,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
      "X-Robots-Tag": "noindex",
      ...SECURITY_HEADERS,
    },
  });
}

function withHeaders(response: Response, options: { preview: boolean; stale: boolean }): Response {
  const headers = new Headers(response.headers);
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) headers.set(name, value);

  if (options.preview) {
    // Belt and braces: the generated page already carries a noindex meta tag
    // for previews, but a crawler that reads headers and skips the body — or a
    // non-HTML response like the sitemap — needs this too.
    headers.set("X-Robots-Tag", "noindex, nofollow");
  }
  if (options.stale) {
    // Observability only. Says the routing answer came from cache past its TTL
    // because the control plane was unreachable, which is otherwise invisible.
    headers.set("X-Tripistic-Route", "stale");
  }

  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

const dispatchWorker = {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    /**
     * The dispatcher's own health endpoint.
     *
     * Namespaced under `/__tripistic/` rather than `/__health` so it cannot
     * collide with a tenant page path — `sitePagePathSchema` reserves
     * `/_tripistic` on the tenant side for the same reason.
     */
    if (url.pathname === "/__tripistic/dispatch-health") {
      return Response.json(
        { ok: true, role: "dispatch", environment: env.ENVIRONMENT ?? "unknown" },
        { headers: { "Cache-Control": "no-store" } },
      );
    }

    const hostname = url.hostname.toLowerCase();
    const lookup = await resolveRoute(hostname, env);

    if (!lookup.found) {
      return errorPage(
        404,
        "Site not found",
        "No published Tripistic website answers on this address. If you have just connected a domain, DNS and certificates can take a few minutes.",
      );
    }

    let tenant: { fetch(request: Request): Promise<Response> };
    try {
      tenant = env.DISPATCHER.get(lookup.route.scriptName);
    } catch {
      // The namespace has no such script: the routing table and the namespace
      // have drifted, usually a deleted script whose deployment row survived.
      return errorPage(
        404,
        "Site not found",
        "This website is not currently deployed. Please try again shortly.",
      );
    }

    try {
      const response = await tenant.fetch(request);
      return withHeaders(response, { preview: lookup.route.preview, stale: lookup.stale });
    } catch {
      // The tenant Worker threw. Never surface the reason: it is generated
      // code, but the message could still echo content, and a stack trace on a
      // customer's homepage helps nobody.
      return errorPage(
        500,
        "This page is temporarily unavailable",
        "Something went wrong rendering this site. The operator has been notified.",
      );
    }
  },
};

export default dispatchWorker;
